name: Marie Tahan
favicon: null
layout_spectrum: 0.92185
typography_spectrum: 1
title: Marie Tahan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a0000'
    - '#885b3c'
    - '#be0000'
    - '#f97784'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
