name: Marie Tahan
favicon: null
layout_spectrum: 0.92185
typography_spectrum: 1
title: Marie Tahan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090303'
    - '#b6b2aa'
    - '#647c81'
    - '#da8463'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
